In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

2022-03-22 08:32:49.618001: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0


In [2]:
x = tf.constant([[10.]]) # matrix 형태.
print(x.shape)

(1, 1)


2022-03-22 08:32:50.275109: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2022-03-22 08:32:50.342093: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-22 08:32:50.344433: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.69GiB deviceMemoryBandwidth: 871.81GiB/s
2022-03-22 08:32:50.344520: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2022-03-22 08:32:50.351767: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2022-03-22 08:32:50.351886: I tensorflow/stream_executor/platform/

In [3]:
x2 = tf.constant([[10.], [20.]])
print(x2.shape)

x3 = tf.constant([[10.], [20.], [30.]])
print(x3) # Column vector 형태

(2, 1)
tf.Tensor(
[[10.]
 [20.]
 [30.]], shape=(3, 1), dtype=float32)


In [4]:
dense = Dense(units=1, activation="linear") # Affine Function. weight와 bias를 가지고 있는 parametric-function + Activation func

In [5]:
y_tf = dense(x) # z = xw + b. 값을 통과시켜주기 전까지는 dense내 weight와 bias가 생성되지 않음.
print(y_tf)

2022-03-22 08:32:50.830973: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11


tf.Tensor([[-7.534998]], shape=(1, 1), dtype=float32)


2022-03-22 08:32:51.209490: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11


In [6]:
W, B = dense.get_weights()
print(W, B)

[[-0.7534998]] [0.]


In [8]:
print("==== Input/Weight/Bias ====")
print(f"x : {x.shape}, {x.numpy()}")
print(f"W : {W.shape}, {W}")
print(f"B : {B.shape}, {B}")      

==== Input/Weight/Bias ====
x : (1, 1), [[10.]]
W : (1, 1), [[-0.7534998]]
B : (1,), [0.]


In [9]:
y_man = tf.linalg.matmul(x, W) + B # dense layer의 연산 결과를 검증하기 위함.
print(y_man)

print("==== output ====")
print(f"tensorflow y : {y_tf.shape}, {y_tf.numpy()}")
print(f"manual y : {y_man.shape}, {y_man.numpy()}")

tf.Tensor([[-7.534998]], shape=(1, 1), dtype=float32)
==== output ====
tensorflow y : (1, 1), [[-7.534998]]
manual y : (1, 1), [[-7.534998]]


In [10]:
from tensorflow.keras.initializers import Constant

w, b = tf.constant(10.), tf.constant(20.)
w_init, b_init = Constant(w), Constant(b)

print(w_init, b_init)

<tensorflow.python.keras.initializers.initializers_v2.Constant object at 0x7f0aa4235fa0> <tensorflow.python.keras.initializers.initializers_v2.Constant object at 0x7f0ac05e2370>


In [11]:
dense = Dense(units=1,
              activation='linear',
              kernel_initializer=w_init,
              bias_initializer=b_init)

In [12]:
y_tf = dense(x)

In [13]:
W, B = dense.get_weights()

In [14]:
print(f"W : {W.shape}, {W}")
print(f"B : {B.shape}, {B}")

W : (1, 1), [[10.]]
B : (1,), [20.]


In [15]:
print(y_tf) # xw+b의 결과. 10 * 10 + 20

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)


In [18]:
x = tf.random.uniform(shape=(1, 10), minval=0, maxval=10)
print(x.shape, '\n', x)

(1, 10) 
 tf.Tensor(
[[4.8429084 3.2975495 4.136052  7.416271  2.7282536 4.2255507 6.451907
  3.447169  6.595587  9.278078 ]], shape=(1, 10), dtype=float32)


In [20]:
dense = Dense(units=1)

y_tf = dense(x)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B

In [23]:
print("==== Input/Weight/Bias ====")
print(f"x : {x.shape}, \n {x.numpy()} \n")
print(f"W : {W.shape}, \n {W} \n")
print(f"B : {B.shape}, \n {B} \n")      


print("==== output ====")
print(f"tensorflow y : {y_tf.shape}, \n {y_tf.numpy()} \n")
print(f"manual y : {y_man.shape}, \n {y_man.numpy()}")

==== Input/Weight/Bias ====
x : (1, 10), 
 [[4.8429084 3.2975495 4.136052  7.416271  2.7282536 4.2255507 6.451907
  3.447169  6.595587  9.278078 ]] 

W : (10, 1), 
 [[ 0.33466452]
 [-0.3409725 ]
 [-0.65490174]
 [-0.43329835]
 [-0.31194615]
 [ 0.05520087]
 [ 0.02141529]
 [-0.49772215]
 [-0.5179281 ]
 [ 0.57549936]] 

B : (1,), 
 [0.] 

==== output ====
tensorflow y : (1, 1), 
 [[-5.6976786]] 

manual y : (1, 1), 
 [[-5.6976786]]
