신경망은 분류와 회귀 모두에 사용할 수 있으 둘 중 어떤 문제인가에 따라 출력층에서 사용하는 활성화 함수가 달라진다.  
일반적으로 회귀에는 항등 함수, 분류에는 소프트맥스 함수를 사용한다.

- 분류는 데이터가 어느 클래스에 속하는가
- 회귀는 입력 데이터에서 수치를 예측하는 문제.

항등 함수는 입력을 그대로 출력한다. 그래서 출력층에서 항등 함수를 사용하면 입력 신호가 그대로 출력 신호가 된다.
<img src="img/deep_learning_images/fig_3-21.png" width=224 height=224>

소프트맥스 함수
<img src="img/deep_learning_images/e_3.10.png" width=224 height=224>
- $n$은 출력층의 뉴런 수.
- $y_k$는 그 중 k번째 출력이다.
- $a_k$는 입력신호

분자는 입력신호 $a_k$의 지수 함수. 분모는 모든 입력 신호의 지수 함수의 합.  
분모가 모든 입력 신호이기 때문에 소프트맥스의 출력은 모든 입력 신호로부터 화살표를 받는다.
<img src="img/deep_learning_images/fig_3-22.png" width=224 height=224>

또 소프트맥스 함수의 출력은 0에서 1.0사이의 실수이고, 출력의 총합은 항상 1이다.  
따라서 소프트맥스 함수의 출력을 확률로 해석할 수 있다.

In [3]:
import numpy as np

In [2]:
a = np.array([0.3, 2.9, 4.0])

In [3]:
exp_a = np.exp(a)
exp_a

array([ 1.34985881, 18.17414537, 54.59815003])

In [4]:
sum_exp_a = np.sum(exp_a)
sum_exp_a

74.1221542101633

In [6]:
y = exp_a / sum_exp_a
y

array([0.01821127, 0.24519181, 0.73659691])

In [1]:
def softmax(x):
    c = np.max(x)
    exp_x = np.exp(x - c)
    sum_exp_x = np.sum(exp_x)
    y = exp_x / sum_exp_x
    
    return y

In [4]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
y

array([0.01821127, 0.24519181, 0.73659691])