수학에서는 1차원 배열은 Vector, 2차원 배열은 Matrix라고 부른다. 또 벡터와 행렬을 일반화한 것을 Tensor라고 한다.

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [3]:
A.shape

(2, 2)

In [4]:
A.dtype

dtype('int64')

### ***BroadCast***

형상이 같은 행렬끼리면 행렬의 산술 연산도 대응하는 원소별로 계산된다.

뿐만 아니라 행렬과 스칼라값의 연산, 형상이 다른 배열끼리도 계산이 가능하다.

In [5]:
A * 10

array([[10, 20],
       [30, 40]])

In [6]:
A = np.array([[1, 2], [3, 4]]) # 2차원 배열
B = np.array([10, 20]) # 1차원 배열

print(A.shape)
print(B.shape)

(2, 2)
(2,)


In [7]:
A * B

array([[10, 40],
       [30, 80]])

### 원소 접근
원소의 인덱스는 0부터 시작한다. 그리고 각 원소에 접근하려면 다음과 같다.

In [8]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)
print(X.ndim)

[[51 55]
 [14 19]
 [ 0  4]]
2


In [9]:
X[0]

array([51, 55])

In [10]:
X[0][1]

55

In [11]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


***flatten()***을 사용하면 행렬을 1차원 배열로 변환할 수 있다.

In [12]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [13]:
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [14]:
X > 15

array([ True,  True, False,  True, False, False])

In [15]:
X[X > 15]

array([51, 55, 19])

In [16]:
test1 = np.array([1, 2, 3, 4, 5, 6, 7])
test2 = np.array([2, 4, 6])

In [17]:
test1[test2]

array([3, 5, 7])

In [18]:
test2 > 5

array([False, False,  True])

In [19]:
test2[test2 > 5]

array([6])